import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { ReactNode } from "react";
import { inter } from "./fonts";
import classNames from "classnames";
import StoreProvider from "./StoreProvider";
import Image from "next/image";

import undulate1 from "./assets/undulate1.svg";
import undulate2 from "./assets/undulate2.svg";
import undulate3 from "./assets/undulate3.svg";
import blob1 from "./assets/blob.svg";
import gradientBG from "./assets/gradientBG.png";

export const metadata: Metadata = {
    title: "Moya Portfolio",
    description: "Generated by JB Moya",
};

export default function RootLayout({
    children,
    about,
    skills,
    projects,
    contacts,
}: {
    children: ReactNode;
    about: ReactNode;
    skills: ReactNode;
    projects: ReactNode;
    contacts: ReactNode;
}) {
    const svgStyle = {
        position: "fixed",
        userSelect: "none",
        pointerEvents: "none",
        zIndex: "1",
    };

    return (
        <html
            lang="en"
            className={classNames(
                `transition-colors duration-700`,
                inter.className
            )}
            data-theme="dark"
        >
            <body className="relative box-border">
                <div className="hehe"></div>
                <div className="w-full">
                    <StoreProvider>
                        <Navbar />
                        {/* <div className="hehe"></div> */}

                        {/* <Image className="fixed -z-10" src={gradientBG} alt="" quality={100}/> */}

                        <main
                            className={classNames(
                                "min-w-3xl max-w-3xl mx-auto px-2 space-y-6 text-custom-content-2"
                            )}
                        >
                            {children}
                            {about}
                            {skills}
                            {projects}
                            {contacts}
                        </main>

                        <Navbar useFooter />
                    </StoreProvider>
                </div>
            </body>
        </html>
    );
}
