import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { ReactNode } from "react";
import { inter } from "./fonts";
import classNames from "classnames";
import StoreProvider from "./StoreProvider";
export const metadata: Metadata = {
    title: "Moya Portfolio",
    description: "Generated by JB Moya",
};

export default function RootLayout({
    children,
    about,
    skills,
    projects,
    contacts,
}: {
    children: ReactNode;
    about: ReactNode;
    skills: ReactNode;
    projects: ReactNode;
    contacts: ReactNode;
}) {
    return (
        <html
            lang="en"
            className={`bg-gradient-to-r from-custom-bg-1 via-custom-bg-2 to-custom-bg-3 transition-colors duration-700 ${inter.className}`}
            data-theme="dark"
        >
            <body className="bg-dot-black/[0.2] relative">
                <StoreProvider>
                    <Navbar />
                    <main
                        className={classNames(
                            "max-w-7xl mx-auto px-2 space-y-6 text-custom-content-2"
                        )}
                    >
                        {children}
                        {about}
                        {skills}
                        {projects}
                        {contacts}
                    </main>
                    {/* <Footer /> */}
                    <Navbar />
                </StoreProvider>
            </body>
        </html>
    );
}
